### ISSUE TITLE
Peer to Peer Review: 10.01.2020

### ISSUE THREAD

**Issue by rmauritsson** [SofiBretz/building_facebook#10]
Review for Milestone 5 and 6

**Comment by noomdalv** [comment]
good job so far 👍

**Comment by KerronKing** [comment]
The project is coming along quite nicely so far. Just remember to display only the posts of the current logged in user and everyone that that user is friends with. You can define a method (that uses SQL) in your user model and use it in your controller to retrieve only those posts in the newsfeed/index page.
