### ISSUE TITLE
Peer-to-Peer Review: Team Power Rangers

### ISSUE THREAD

**Issue by rmauritsson** [SofiBretz/building_facebook#2]
Review for Milestone 1 and 2

**Comment by KerronKing** [comment]
Everything looks good for the most part. Just make the small edits to the diagram as we discussed. Good luck with the rest of the project!

**Comment by RoyNyaga** [comment]
Good structure, just some little fix. One to one relationship is represented using a link from the id to the model field representing the relationship and not from id to id.
